---
- hosts: all
  become: yes
  roles:
    - role: ansible-nginx
    - role: ansible-letsencrypt
      letsencrypt_domains: "{{ nginx_sites.default.domains }}"
  tasks:
  - name: Create webroot directories
    file: 
      path: "{{ item.value.root }}"
      state: directory
      owner: www-data
      group: speedmann
      mode: 0774
    with_dict: "{{ nginx_sites }}"
