---
- hosts: all
  become: yes
  roles:
    - role: ansible-nginx
    - role: ansible-letsencrypt
      letsencrypt_domains: "{{ nginx_sites.default.domains }}"
  tasks:
  - name: debug item
    debug:
      var:{{ item }}
    with_dict: "{{ nginx_sites }}"
  - name: Create webroot directories
    file: 
      path: "{{ item.value.root }}"
      state: directory
    with_dict: "{{ nginx_sites }}"
